apiVersion: v1
kind: Service
metadata:
  name: kibana-np
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - name: client
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 31601
  selector:
    app: kibana 

