apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI5IiwgR2l0VmVyc2lvbjoidjEuOS4xKzIuMS44LmVsNyIsIEdpdENvbW1pdDoiOGZkNjZmYzY5Njc2NzJkZjMwN2MyZDk0ZGQ1MDQ4MDAxOTNmNmYzYyIsIEdpdFRyZWVTdGF0ZToiYXJjaGl2ZSIsIEJ1aWxkRGF0ZToiMjAxOC0wNS0yMVQxMzowOTozOVoiLCBHb1ZlcnNpb246ImdvMS45LjQiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwKyIsIEdpdFZlcnNpb246InYxLjEwLjMtMitiMzVjOGYwMmI3OTg1NSIsIEdpdENvbW1pdDoiYjM1YzhmMDJiNzk4NTVjNzYyYjBkYTNhZmRjNjQzYmExYWVmMWNhOSIsIEdpdFRyZWVTdGF0ZToiY2xlYW4iLCBCdWlsZERhdGU6IjIwMTgtMDYtMDFUMjE6MDM6NDJaIiwgR29WZXJzaW9uOiJnbzEuOS4zIiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0K",
              "date": "Thu Sep 20 2018 11:04:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
      namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI5IiwgR2l0VmVyc2lvbjoidjEuOS4xKzIuMS44LmVsNyIsIEdpdENvbW1pdDoiOGZkNjZmYzY5Njc2NzJkZjMwN2MyZDk0ZGQ1MDQ4MDAxOTNmNmYzYyIsIEdpdFRyZWVTdGF0ZToiYXJjaGl2ZSIsIEJ1aWxkRGF0ZToiMjAxOC0wNS0yMVQxMzowOTozOVoiLCBHb1ZlcnNpb246ImdvMS45LjQiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwKyIsIEdpdFZlcnNpb246InYxLjEwLjMtMitiMzVjOGYwMmI3OTg1NSIsIEdpdENvbW1pdDoiYjM1YzhmMDJiNzk4NTVjNzYyYjBkYTNhZmRjNjQzYmExYWVmMWNhOSIsIEdpdFRyZWVTdGF0ZToiY2xlYW4iLCBCdWlsZERhdGU6IjIwMTgtMDYtMDFUMjE6MDM6NDJaIiwgR29WZXJzaW9uOiJnbzEuOS4zIiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0K",
              "date": "Thu Sep 20 2018 11:04:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI5IiwgR2l0VmVyc2lvbjoidjEuOS4xKzIuMS44LmVsNyIsIEdpdENvbW1pdDoiOGZkNjZmYzY5Njc2NzJkZjMwN2MyZDk0ZGQ1MDQ4MDAxOTNmNmYzYyIsIEdpdFRyZWVTdGF0ZToiYXJjaGl2ZSIsIEJ1aWxkRGF0ZToiMjAxOC0wNS0yMVQxMzowOTozOVoiLCBHb1ZlcnNpb246ImdvMS45LjQiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwKyIsIEdpdFZlcnNpb246InYxLjEwLjMtMitiMzVjOGYwMmI3OTg1NSIsIEdpdENvbW1pdDoiYjM1YzhmMDJiNzk4NTVjNzYyYjBkYTNhZmRjNjQzYmExYWVmMWNhOSIsIEdpdFRyZWVTdGF0ZToiY2xlYW4iLCBCdWlsZERhdGU6IjIwMTgtMDYtMDFUMjE6MDM6NDJaIiwgR29WZXJzaW9uOiJnbzEuOS4zIiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0K",
              "date": "Thu Sep 20 2018 11:04:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
      namespace: kube-system
    roleRef:
      kind: Role
      name: admin 
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/net?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI5IiwgR2l0VmVyc2lvbjoidjEuOS4xKzIuMS44LmVsNyIsIEdpdENvbW1pdDoiOGZkNjZmYzY5Njc2NzJkZjMwN2MyZDk0ZGQ1MDQ4MDAxOTNmNmYzYyIsIEdpdFRyZWVTdGF0ZToiYXJjaGl2ZSIsIEJ1aWxkRGF0ZToiMjAxOC0wNS0yMVQxMzowOTozOVoiLCBHb1ZlcnNpb246ImdvMS45LjQiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwKyIsIEdpdFZlcnNpb246InYxLjEwLjMtMitiMzVjOGYwMmI3OTg1NSIsIEdpdENvbW1pdDoiYjM1YzhmMDJiNzk4NTVjNzYyYjBkYTNhZmRjNjQzYmExYWVmMWNhOSIsIEdpdFRyZWVTdGF0ZToiY2xlYW4iLCBCdWlsZERhdGU6IjIwMTgtMDYtMDFUMjE6MDM6NDJaIiwgR29WZXJzaW9uOiJnbzEuOS4zIiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0K",
              "date": "Thu Sep 20 2018 11:04:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-net
      namespace: kube-system
    spec:
      minReadySeconds: 5
      template:
        metadata:
          labels:
            name: weave-net
        spec:
          containers:
            - name: weave
              command:
                - /home/weave/launch.sh
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: 'docker.io/weaveworks/weave-kube:2.4.1'
              livenessProbe:
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
                initialDelaySeconds: 30
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
              volumeMounts:
                - name: weavedb
                  mountPath: /weavedb
                - name: cni-bin
                  mountPath: /host/opt
                - name: cni-bin2
                  mountPath: /host/home
                - name: cni-conf
                  mountPath: /host/etc
                - name: dbus
                  mountPath: /host/var/lib/dbus
                - name: lib-modules
                  mountPath: /lib/modules
                - name: xtables-lock
                  mountPath: /run/xtables.lock
            - name: weave-npc
              args: []
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: 'docker.io/weaveworks/weave-npc:2.4.1'
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
              volumeMounts:
                - name: xtables-lock
                  mountPath: /run/xtables.lock
          hostNetwork: true
          hostPID: true
          restartPolicy: Always
          securityContext:
            seLinuxOptions: {}
          serviceAccountName: weave-net
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: weavedb
              hostPath:
                path: /var/lib/weave
            - name: cni-bin
              hostPath:
                path: /opt
            - name: cni-bin2
              hostPath:
                path: /home
            - name: cni-conf
              hostPath:
                path: /etc
            - name: dbus
              hostPath:
                path: /var/lib/dbus
            - name: lib-modules
              hostPath:
                path: /lib/modules
            - name: xtables-lock
              hostPath:
                path: /run/xtables.lock
                type: FileOrCreate
      updateStrategy:
        type: RollingUpdate
