apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitorshop
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 31190
  selector:
    app: prometheus
