apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitorshop
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
  selector:
    app: kube-state-metrics
