apiVersion: v1
kind: Service
metadata:
  name: kubeapps-np
  namespace: kubeapps
spec:
  type: NodePort
  selector:
    app: kubeapps
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
  selector:
    app: kubeapps

